spring:
  application:
    name: ek-server
eureka:
  instance:
    lease-renewal-interval-in-seconds: 2
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka
logging:
  level:
    com.qimh: debug

